### ISSUE TITLE
command line arguments not passing well

### ISSUE THREAD

**Issue by orevron** [nadavsky/node-watchdog#1]
## problem:
starting my script with the following command:

>node watchdog.js --watchdog_requireUrl http://localhost/capriza-ng/test/watchdog-components/ --watchdog_outputPath /data/capriza-ng/log

but requireUrl is not updating and outputPath stays at ~/watchdog

## gist
https://gist.github.com/orevron/c0ff345eded9c64d9f265d46a1b02e0f

**Comment by orevron** [comment]
![image](https://user-images.githubusercontent.com/20145882/37144586-3045a5fc-22c7-11e8-9936-922b964f5896.png)

another error regarding the command line arguments

**Comment by nadavsky** [comment]
> ## problem:
> starting my script with the following command:
> 
> > node watchdog.js --watchdog_requireUrl http://localhost/capriza-ng/test/watchdog-components/ --watchdog_outputPath /data/capriza-ng/log
> 
> but requireUrl is not updating and outputPath stays at ~/watchdog
> 
> ## gist
> https://gist.github.com/orevron/c0ff345eded9c64d9f265d46a1b02e0f

fixed!
